spring.application.name=sitiopc
# PostgreSQL (Railway)
spring.datasource.url=jdbc:postgresql://postgres:RbewKLJrSHyflwnfNSkJOdXTIqPoVswj@thomas.proxy.rlwy.net:38412/railway
spring.datasource.username=postgres
spring.datasource.password=RbewKLJrSHyflwnfNSkJOdXTIqPoVswj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# Servidor
server.port=8081