spring.application.name=sitiopc

# PostgreSQL (Railway)
spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:38412/railway
spring.datasource.username=postgres
spring.datasource.password=gvPaPpzAiqCHQbwwygOkujwXyzSJAxOG
spring.datasource.driver-class-name=org.postgresql.Driver

# SSL requerido por Railway
spring.datasource.hikari.data-source-properties.sslmode=require

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# Servidor
server.port=8081

# JWT
jwt.secret=super_secret_key_change_me_123456789_super_long_key
jwt.expiration=3600000